/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionIcon: typeof import('./src/components/VideoDetail.vue/VideoActionBar/ActionIcon.vue')['default']
    AdBanner: typeof import('./src/components/VideoDetail.vue/AdBanner.vue')['default']
    AIReply: typeof import('./src/components/AI/AIReply.vue')['default']
    CommonVideosCard: typeof import('./src/components/Home/CommonVideosCard.vue')['default']
    CommonVideosCardccopy: typeof import('./src/components/Home/CommonVideosCardccopy.vue')['default']
    EpisodeGrid: typeof import('./src/components/VideoDetail.vue/EpisodeSelector/EpisodeGrid.vue')['default']
    EpisodeItem: typeof import('./src/components/VideoDetail.vue/EpisodeSelector/EpisodeItem.vue')['default']
    EpisodeSelector: typeof import('./src/components/VideoDetail.vue/EpisodeSelector/index.vue')['default']
    ExpandableText: typeof import('./src/components/VideoDetail.vue/VideoMetaInfo/ExpandableText.vue')['default']
    Index: typeof import('./src/components/VideoDetail.vue/VideoMetaInfo/Index.vue')['default']
    Loading: typeof import('./src/components/Home/Loading.vue')['default']
    MySearch: typeof import('./src/components/Home/MySearch.vue')['default']
    PopularVideosCard: typeof import('./src/components/Home/PopularVideosCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Home/Search.vue')['default']
    Start: typeof import('./src/components/Assistant/Start.vue')['default']
    Svip: typeof import('./src/components/VideoDetail.vue/Svip.vue')['default']
    TabBar: typeof import('./src/components/Home/TabBar.vue')['default']
    TabFilter: typeof import('./src/components/VideoDetail.vue/EpisodeSelector/TabFilter.vue')['default']
    TagBadge: typeof import('./src/components/VideoDetail.vue/VideoMetaInfo/TagBadge.vue')['default']
    UploadArea: typeof import('./src/components/Mine/Upload/UploadArea.vue')['default']
    UploadProgressItem: typeof import('./src/components/Mine/Upload/UploadProgressItem.vue')['default']
    UpVideo: typeof import('./src/components/VideoDetail.vue/upVideo.vue')['default']
    UserQuery: typeof import('./src/components/AI/UserQuery.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanDivider: typeof import('vant/es')['Divider']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VideoActionBar: typeof import('./src/components/VideoDetail.vue/VideoActionBar/VideoActionBar.vue')['default']
    VideoList: typeof import('./src/components/VideoDetail.vue/VideoList.vue')['default']
    VideoMetaInfo: typeof import('./src/components/VideoDetail.vue/VideoMetaInfo/VideoMetaInfo.vue')['default']
    VideoPlayer: typeof import('./src/components/VideoDetail.vue/VideoPlayer.vue')['default']
    VipPromotionBanner: typeof import('./src/components/VideoDetail.vue/VipPromotionBanner.vue')['default']
  }
}
