/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIReply: typeof import('./src/components/AI/AIReply.vue')['default']
    CommonVideosCard: typeof import('./src/components/Home/CommonVideosCard.vue')['default']
    Loading: typeof import('./src/components/Home/Loading.vue')['default']
    PopularVideosCard: typeof import('./src/components/Home/PopularVideosCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Start: typeof import('./src/components/Assistant/Start.vue')['default']
    TabBar: typeof import('./src/components/Home/TabBar.vue')['default']
    UserQuery: typeof import('./src/components/AI/UserQuery.vue')['default']
    VanIcon: typeof import('vant/es')['Icon']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
